/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author weiliu
 */
package userInterface;

public class szbutton extends javax.swing.JPanel {

    /**
     * Creates new form Main
     */
    public szbutton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        xilihu = new javax.swing.JButton();
        shandong = new javax.swing.JButton();
        daxuecheng = new javax.swing.JButton();
        tanglang = new javax.swing.JButton();
        chaguang = new javax.swing.JButton();
        zhuguang = new javax.swing.JButton();
        longjing = new javax.swing.JButton();
        changlingpo = new javax.swing.JButton();
        xili = new javax.swing.JButton();
        taoyuancun = new javax.swing.JButton();
        shenyun = new javax.swing.JButton();
        antuoshan = new javax.swing.JButton();
        nonglin = new javax.swing.JButton();
        qiaoxiang = new javax.swing.JButton();
        xiangmi = new javax.swing.JButton();
        xiangmeibei = new javax.swing.JButton();
        jingtian = new javax.swing.JButton();
        xiangmei = new javax.swing.JButton();
        chegongmiao = new javax.swing.JButton();
        shenwan = new javax.swing.JButton();
        shenzhenwangongyuan = new javax.swing.JButton();
        xiasha = new javax.swing.JButton();
        huaqiaocheng = new javax.swing.JButton();
        qiaochengdong = new javax.swing.JButton();
        zhuzilin = new javax.swing.JButton();
        meijing = new javax.swing.JButton();
        xiameilin = new javax.swing.JButton();
        meicun = new javax.swing.JButton();
        lianhuaxi = new javax.swing.JButton();
        futian = new javax.swing.JButton();
        huizhenzhongxin = new javax.swing.JButton();
        gouwugongyuan = new javax.swing.JButton();
        xiangmihu = new javax.swing.JButton();
        shangsha = new javax.swing.JButton();
        shawei = new javax.swing.JButton();
        shisha = new javax.swing.JButton();
        huanggangcun = new javax.swing.JButton();
        dajuyuan = new javax.swing.JButton();
        shaoniangong = new javax.swing.JButton();
        lianhuabei = new javax.swing.JButton();
        shiminzhongxin = new javax.swing.JButton();
        gangshabei = new javax.swing.JButton();
        gangsha = new javax.swing.JButton();
        fumin = new javax.swing.JButton();
        huanggangkouan = new javax.swing.JButton();
        chiwei = new javax.swing.JButton();
        shangmeiling = new javax.swing.JButton();
        shenzhenbeizhan = new javax.swing.JButton();
        lianhuacun = new javax.swing.JButton();
        huaqiangbei = new javax.swing.JButton();
        tongxinling = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sz.png"))); // NOI18N

        jLayeredPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(539, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        xilihu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xilihuActionPerformed(evt);
            }
        });

        shandong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shandongActionPerformed(evt);
            }
        });

        longjing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longjingActionPerformed(evt);
            }
        });

        meijing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meijingActionPerformed(evt);
            }
        });

        huanggangcun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huanggangcunActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(xilihu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(shandong, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(daxuecheng, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(tanglang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(chaguang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(zhuguang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(longjing, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(changlingpo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(xili, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(taoyuancun, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(shenyun, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(antuoshan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(nonglin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(qiaoxiang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(xiangmi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(xiangmeibei, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jingtian, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(xiangmei, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(chegongmiao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(shenwan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(shenzhenwangongyuan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(xiasha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(huaqiaocheng, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(qiaochengdong, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(zhuzilin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(meijing, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(xiameilin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(meicun, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lianhuaxi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(futian, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(huizhenzhongxin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(gouwugongyuan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(xiangmihu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(shangsha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(shawei, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(shisha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(huanggangcun, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(dajuyuan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(shaoniangong, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lianhuabei, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(shiminzhongxin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(gangshabei, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(gangsha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(fumin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(huanggangkouan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(chiwei, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(shangmeiling, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(shenzhenbeizhan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lianhuacun, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(huaqiangbei, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(tongxinling, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(huaqiaocheng, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lianhuacun, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(795, Short.MAX_VALUE))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addComponent(qiaochengdong, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(zhuzilin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(shenzhenwangongyuan, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(chegongmiao, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(xiasha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(shangsha, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                                .addGap(114, 114, 114)
                                                .addComponent(huizhenzhongxin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(shawei, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(shaoniangong, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lianhuabei, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(52, 52, 52)
                                .addComponent(huanggangkouan, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(chiwei, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(gangsha, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(388, Short.MAX_VALUE))))
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(shandong, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xilihu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chaguang, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(taoyuancun, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(zhuguang, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(meijing, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane3Layout.createSequentialGroup()
                                                .addGap(79, 79, 79)
                                                .addComponent(changlingpo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23)
                                                .addComponent(tanglang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(daxuecheng, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(11, 11, 11))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane3Layout.createSequentialGroup()
                                                .addGap(124, 124, 124)
                                                .addComponent(xiameilin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(meicun, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(19, 19, 19)
                                        .addComponent(shenzhenbeizhan, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addComponent(xili, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(91, 91, 91))
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                                .addComponent(shenyun, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(64, 64, 64))
                                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(nonglin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(antuoshan, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(shenwan, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(qiaoxiang, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24)
                                                .addComponent(xiangmi, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(xiangmeibei, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tongxinling, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73))
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(xiangmei, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                                        .addComponent(jingtian, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lianhuaxi, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(29, 29, 29)
                                                        .addComponent(futian, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(xiangmihu, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(shisha, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(gouwugongyuan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(shiminzhongxin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(gangshabei, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(57, 57, 57)
                                                        .addComponent(huaqiangbei, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                                        .addGap(1, 1, 1)
                                                        .addComponent(huanggangcun, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(fumin, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(106, 106, 106)
                                                .addComponent(dajuyuan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(longjing, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(shangmeiling, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(xilihu, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shandong, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(xili, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tanglang, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changlingpo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(daxuecheng, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(chaguang, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(zhuguang, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(shangmeiling, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(meicun, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(xiameilin, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(38, 38, 38)))
                        .addComponent(longjing, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(taoyuancun, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meijing))
                        .addGap(17, 17, 17)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(lianhuacun, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(shenyun, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tongxinling, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(futian, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(xiangmeibei, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(xiangmi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(antuoshan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(qiaoxiang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(21, 21, 21)
                                        .addComponent(nonglin, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lianhuaxi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jingtian, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(8, 8, 8))
                                                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                                    .addComponent(dajuyuan, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(14, 14, 14))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane3Layout.createSequentialGroup()
                                                    .addComponent(gangshabei, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(huaqiangbei, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(shiminzhongxin, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(22, 22, 22)))
                                        .addComponent(xiangmei, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(huaqiaocheng, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(qiaochengdong, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(chegongmiao, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(zhuzilin, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gouwugongyuan, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(huizhenzhongxin, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(gangsha, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(xiangmihu, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)))
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xiasha, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shenzhenwangongyuan, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shenwan, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(shisha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(shawei, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fumin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(huanggangkouan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chiwei, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(huanggangcun, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(130, 130, 130))
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(shangsha, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(shenzhenbeizhan, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(lianhuabei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(shaoniangong, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(336, 336, 336))))
        );

        jLayeredPane1.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLayeredPane3, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(630, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(294, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1119, 1119, 1119)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xilihuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xilihuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xilihuActionPerformed

    private void shandongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shandongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shandongActionPerformed

    private void longjingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longjingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longjingActionPerformed

    private void meijingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meijingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meijingActionPerformed

    private void huanggangcunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huanggangcunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_huanggangcunActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton antuoshan;
    private javax.swing.JButton chaguang;
    private javax.swing.JButton changlingpo;
    private javax.swing.JButton chegongmiao;
    private javax.swing.JButton chiwei;
    private javax.swing.JButton dajuyuan;
    private javax.swing.JButton daxuecheng;
    private javax.swing.JButton fumin;
    private javax.swing.JButton futian;
    private javax.swing.JButton gangsha;
    private javax.swing.JButton gangshabei;
    private javax.swing.JButton gouwugongyuan;
    private javax.swing.JButton huanggangcun;
    private javax.swing.JButton huanggangkouan;
    private javax.swing.JButton huaqiangbei;
    private javax.swing.JButton huaqiaocheng;
    private javax.swing.JButton huizhenzhongxin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JButton jingtian;
    private javax.swing.JButton lianhuabei;
    private javax.swing.JButton lianhuacun;
    private javax.swing.JButton lianhuaxi;
    private javax.swing.JButton longjing;
    private javax.swing.JButton meicun;
    private javax.swing.JButton meijing;
    private javax.swing.JButton nonglin;
    private javax.swing.JButton qiaochengdong;
    private javax.swing.JButton qiaoxiang;
    private javax.swing.JButton shandong;
    private javax.swing.JButton shangmeiling;
    private javax.swing.JButton shangsha;
    private javax.swing.JButton shaoniangong;
    private javax.swing.JButton shawei;
    private javax.swing.JButton shenwan;
    private javax.swing.JButton shenyun;
    private javax.swing.JButton shenzhenbeizhan;
    private javax.swing.JButton shenzhenwangongyuan;
    private javax.swing.JButton shiminzhongxin;
    private javax.swing.JButton shisha;
    private javax.swing.JButton tanglang;
    private javax.swing.JButton taoyuancun;
    private javax.swing.JButton tongxinling;
    private javax.swing.JButton xiameilin;
    private javax.swing.JButton xiangmei;
    private javax.swing.JButton xiangmeibei;
    private javax.swing.JButton xiangmi;
    private javax.swing.JButton xiangmihu;
    private javax.swing.JButton xiasha;
    private javax.swing.JButton xili;
    private javax.swing.JButton xilihu;
    private javax.swing.JButton zhuguang;
    private javax.swing.JButton zhuzilin;
    // End of variables declaration//GEN-END:variables
}
